### ISSUE TITLE
Plugin doesnt seem to work, or unable to launch it.

### ISSUE THREAD

**Issue by vailshnast** [ReallyLiri/no-namespace-providers-rider-plugin#1] opened 2021-07-28 13:50 UTC
Dowloaded and installed plugin from marketplace, but it doesnt seem to work. Is there specific actions i need to make in order to make this working? Im using rider with unity, maybe this could be an issue.

https://prnt.sc/1h33a4n
https://prnt.sc/1h33t7b

**Comment by ReallyLiri** [comment] 2021-07-28 13:52
This wasn't tested on Windows, that might be the issue.
Which Rider version are you using?

**Comment by vailshnast** [comment] 2021-07-28 14:14
> This wasn't tested on Windows, that might be the issue.
> Which Rider version are you using?

Rider 2021.1.3 https://prnt.sc/1h3cmim

**Comment by ReallyLiri** [comment] 2021-08-09 08:26
currently the plugin will mark a directory as "not a namespace provider" only on demand -- that is, when its visible in the project explorer.
From your screenshot I'm guessing the directory IS visible in Rider, right?
Do you get any exception logs from Rider? should be appearing in a bottom right corner, or in Event Log

![image](https://user-images.githubusercontent.com/16985735/128682252-04445ac5-600a-4d06-b43e-800d76d75980.png)

**Comment by vailshnast** [comment] 2021-08-10 15:13
Unfortunatly no messages in Event log.
Yeah it is Unity Project, and all folders are visible in Rider.
Is there any button to make all folders "non providers", if auto feature doesnt work? 
https://prnt.sc/1mbgr84

**Comment by ReallyLiri** [comment] 2021-08-13 12:05
Great idea, working on this feature

**Comment by ReallyLiri** [comment] 2021-08-14 11:45
v1.6 is released with a new feature to apply on entire solution on demand. Please update and try :)
![nRXlwG5](https://user-images.githubusercontent.com/16985735/129445265-69a48c87-9fa3-42a6-a6a0-81cfb5649772.png)
![18AAo1R](https://user-images.githubusercontent.com/16985735/129445267-50469682-6a30-4460-acf8-c46e0ebb047a.png)
![V1Ed2CM](https://user-images.githubusercontent.com/16985735/129445268-daf688fd-7951-41ab-809c-7acfc5aca403.png)

**Comment by vailshnast** [comment] 2021-08-14 14:59
I`ve just updated plugin, tried on non unity project. Noticed several things:
1. Auto feature does work on first project, however after adding at least on script to folder.
2. Button does never detects updates, as you can see from video event log.
3. On other projects nothing works unfortunatly.

Maybe i configured something wrong, or this doesnt realy work on windows, however you are doing amazing job, thanks in advance!

https://user-images.githubusercontent.com/23454812/129450430-9b3a1127-b4f5-4c98-b914-9627b488c4b7.mp4

**Comment by ReallyLiri** [comment] 2021-08-15 06:57
Thanks, I'll try to reproduce this flow, hopefully will get to it in next few days. I'm also trying to get a Windows machine to try this on. Will update :)

**Comment by ReallyLiri** [comment] 2021-08-23 16:26
I published another version `1.7`, with a more "brute force" approach to apply the configuration.

Next week I know I can try to debug the plugin on a Windows machine and will update. Thanks for your time!

**Comment by vailshnast** [comment] 2022-01-19 04:43
`<s:Boolean x:Key="/Default/CodeInspection/NamespaceProvider/NamespaceFoldersToSkip/=assets/games/@EntryIndexedValue">True</s:Boolean>`

`<s:Boolean x:Key="/Default/CodeInspection/NamespaceProvider/NamespaceFoldersToSkip/=assets_005Cgames/@EntryIndexedValue">True</s:Boolean>
`
I digged to dotsettings that rider is generating, first line is not working, which is generated by your plugin, the second one is when i do it manually. What is the reason for that?(

I could guess the problem is with / \ symbols

**Comment by liiri** [comment] 2022-01-19 08:26
yes, it seems to be missing escaping. I probably only handled unix styled paths and not Windows, and that's where the gap is :)

**Comment by ReallyLiri** [comment] 2022-01-19 08:27
yes, it seems to be missing escaping. I probably only handled unix styled paths and not Windows, and that's where the gap is :)

**Comment by ReallyLiri** [comment] 2022-01-29 12:37
version 1.8 of the plugin is published with the path encoding fixed, please test it
ref: https://github.com/ReallyLiri/no-namespace-providers-rider-plugin/commit/aa987c0e96af8183aa06cb32c605a7ddbe903187

**Comment by vailshnast** [comment] 2022-01-31 05:21
Working like a charm, thanks!

**Closed as completed** 2022-01-31 08:47 UTC
